services:
  db:
    image: postgres:17
    container_name: ce-db
    env_file: "database/.env"
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coco-network

  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: ce-devcontainer
    volumes:
      - ./:/coco-expenses
    depends_on:
      - db
    networks:
      - coco-network
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: dev
    container_name: ce-nginx
    ports:
      - "3000:80"
    depends_on:
      - devcontainer
    networks:
      - coco-network
    volumes:
      - ./nginx/nginx-devcontainer.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:

networks:
  coco-network:
    driver: bridge
