services:
  db:
    image: postgres:latest
    container_name: ce-db
    env_file: "database/.env"
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coco-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: ce-be
    env_file: "backend/.env"
    environment:
      - DB_HOST=db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - coco-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: ce-fe
    volumes:
      - ./frontend/coco-expenses-v2-frontend/src:/app/src
    networks:
      - coco-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: dev
    container_name: ce-nginx
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - coco-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:

networks:
  coco-network:
    driver: bridge
